### ISSUE TITLE
preferences.jons

### ISSUE THREAD

**Issue by alemotta1974** [Steffenhir/GraXpert#103]
Hello everybody,
When i launch Graxpert (windows10) the application freezer and After a while Is not responding, i checked the log file chat says:
Preferences.jons Is missing
Does anybody had the same issue, any solutions ?
Thx

**Comment by alemotta1974** [comment]
Solved, working !! With tour preferences.json file

**Comment by Shawn25678** [comment]
> Solved, working !! With tour preferences.json file
nice
