### ISSUE TITLE
New download on windows 11 latest and will not even run, just hangs and throws error

### ISSUE THREAD

**Issue by ShedAstro** [Steffenhir/GraXpert#104]
I get this straight after download when I double click the install icon…

**Comment by ShedAstro** [comment]
![IMG_2070](https://github.com/Steffenhir/GraXpert/assets/97532001/0006ff7a-5146-4221-adca-500093d41258)

**Comment by ShedAstro** [comment]
Now tried on 3 different win 11 machines and won’t download until antivirus is disabled, and then it will not run and hangs and throws an error after about 30 seconds…..so there is a real issue here, and wonder if it does include a virus now, as 3 machines can’t be wrong….☹️

**Comment by Shawn25678** [comment]
mine is running on the newest verison and im on win11 and it just kinda sits there on spash screen with the window in the background not responding forever
![failedstart](https://github.com/Steffenhir/GraXpert/assets/119130434/66cb77e7-aee9-4987-a9f0-3a9a220c8f14)

**Comment by ShedAstro** [comment]
> mine is running on the newest verison and im on win11 and it just kinda sits there on splash screen with the window in the background not responding forever ![failedstart](https://private-user-images.githubusercontent.com/119130434/289386868-66cb77e7-aee9-4987-a9f0-3a9a220c8f14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNTA5NjYsIm5iZiI6MTcwMjI1MDY2NiwicGF0aCI6Ii8xMTkxMzA0MzQvMjg5Mzg2ODY4LTY2Y2I3N2U3LWFlZTktNDk4Ny1hOWYwLTNhOWEyMjBjOGYxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQyMzI0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmRjNTA5NmQzN2U0YWY5MGI5MzRiZGI5M2NkMjNhZWQ4NTI1MGMyZDkwMGMxZGY1YjVjN2JiNjk4OGI3YTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MwhuIc8zY9LXcAS6xPEDGWVqMRBdZhx7OmgADJ3fbns)

I have the splash screen which just sits there, but not the open window behind, then after about 30 seconds I get an error box..

**Comment by Shawn25678** [comment]
so I just figured something out about the program for some reason the program will start in my native res but once I go off my native res it will no load and hang on the splash screen very interesting

**Comment by ShedAstro** [comment]
> so I just figured something out about the program for some reason the program will start in my native res but once I go off my native res it will no load and hang on the splash screen very interesting. this does seem like a issue with window resolution for me not really sure why but hey it works just need a magnifying glass to see text

Hmmm,
Well I have it working now, and I have a 32” 4K monitor, and it works fine, but 4K is the native res, but I do have it set on 125% scaling factor and not the 150% that windows sets as the default…but still work fine…

**Comment by Shawn25678** [comment]
> > so I just figured something out about the program for some reason the program will start in my native res but once I go off my native res it will no load and hang on the splash screen very interesting. this does seem like a issue with window resolution for me not really sure why but hey it works just need a magnifying glass to see text
> 
> Hmmm, Well I have it working now, and I have a 32” 4K monitor, and it works fine, but 4K is the native res, but I do have it set on 125% scaling factor and not the 150% that windows sets as the default…but still work fine…

I got it to scale someone good now at 1080p which is what I wanted to be at one of the devs told me to crank the scale setting in the program which allowed it to start working for some reason on some of the settings I couldnt do before like having windows at 125% scale and 150% scale on 1080p and having fix blurry text on which also bugged it out on hanging cranking the dpi any higher starts the problem again butt im happy with the scale of the ui now being very much seeable

**Comment by Bodrero** [comment]
I have downloaded the installer but when I run it, I get a spinning circle, it goes away and the installer won't continue.  I'm using Windows 11.

Any ideas?
