### ISSUE TITLE
PreRelease 2.1.0: Command Line no more working

### ISSUE THREAD

**Issue by AstroDeepSky** [Steffenhir/GraXpert#112]
I tried GraXpert command line with PreRelease 2.1.0 and got attached error pop-up.
![GraXpert-PreRelease-2 1 0-CLI-Error](https://github.com/Steffenhir/GraXpert/assets/5413326/62c4308a-6f5b-436b-92d5-e13a12675afb)

You did some changes in astroimage.py that impact command line:
![Changes-PreRelease-2 1 0](https://github.com/Steffenhir/GraXpert/assets/5413326/d9345eb5-29b8-4316-a495-2b08847efcd8)

**Comment by Steffenhir** [comment]
Fixed with version 2.1.1
