### ISSUE TITLE
PreRelease 2.1.0: Some command line option missing

### ISSUE THREAD

**Issue by AstroDeepSky** [Steffenhir/GraXpert#113]
In PreRelease 2.1.0, I can see some code to export background model:
![Export-Background](https://github.com/Steffenhir/GraXpert/assets/5413326/a3e6737a-9ef4-4082-91df-f948de58f49a)

However, new arg "-bg" is not declared in main.py.
Will you also add -cli option as it was proposed in Beta 2.0.3test?

Regards

**Comment by Steffenhir** [comment]
Fixed with version 2.1.1
