### ISSUE TITLE
Feature request - normalize

### ISSUE THREAD

**Issue by naixx** [Steffenhir/GraXpert#116]
Hey, great to that works amazing, thank you!

It would be great to have an option to normalize outout, same as DBE have. It can be very useful in some workflows

**Comment by Steffenhir** [comment]
Hi, I think what Pixinsight calls 'normalize output' is already the default behavior of GraXpert. The background model is subtracted from the original image, and then a offset is added such that the average of all pixel values of the image is the same as before.
