### ISSUE TITLE
Drag Graxpert icon to desktop BUG?

### ISSUE THREAD

**Issue by Calzune** [Steffenhir/GraXpert#117]
In previous versions of graxpert in Pixinsight you could drag the icon to desktop so it could be used in a processcontainer, now with version 2.2.0  its not possible anymore.
![Skärmklipp](https://github.com/Steffenhir/GraXpert/assets/44265281/fff58717-8dd3-48dc-82f6-f4750358a32e)

**Comment by schmelly** [comment]
Dear @Calzune

I'll raise your issue with the developer of `GraXpert Script v1.2` (please note the script is not part of this Github project. However, we are in close contact with him).

Best regards and CS
David

**Comment by JuergenTerpe** [comment]
Dear @Calzune,

I have updated the Toolbox package and fixed this issue. Using script version 1.2a you will have again the New Instance button working as expected. Sorry for your inconvenience!
