### ISSUE TITLE
Linux CUDA support

### ISSUE THREAD

**Issue by ihabmmali** [Steffenhir/GraXpert#119]
Hello,
I have CUDA setup and running on my Ubuntu 22.04 and running well with Pixinsight and other plugins. When I start GraXpert from the command line, I get this warning:

tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.

Is there anyway to eanble GPU support on linux with the packaged version of Graxpert?

**Comment by Steffenhir** [comment]
Hi, we intentionally disabled the GPU support to avoid some errors with already installed incompatible drivers. However, in the future we might switch from tensorflow to the ONNX runtime and enable GPU support.

**Comment by schmelly** [comment]
Hi,

CUDA acceleration is now supported by GraXpert 3.0.2 on Linux via onnxruntime. Required Dependencies are:
- CUDA 12
- libcudnn8
- a CUDA 12 compatible kernel module

CS, David
