### ISSUE TITLE
graxpert won't open after update on mac

### ISSUE THREAD

**Issue by bartvanhoyland** [Steffenhir/GraXpert#120]
Hi,

Yesterday I installed the new update of Graxpert on my Macbook with M1 processor.
After downloading and giving permission to open the app it won't open anymore.
The icon of the app pops up but then nothing happens.

Is this a known issue?

Best,

Bart

**Comment by Steffenhir** [comment]
Hi, what macOS version are you using? I built the arm version with macOS 13.6, so maybe a version > 13.6 may be required

**Comment by bartvanhoyland** [comment]
Hi, I’m working on OS 11.7. But before the update all worked, I use itwith the PixinSight script.Will try to update my OS.Thanks,BartVerstuurd vanaf mijn iPhoneOp 12 jan. 2024 om 21:21 heeft Steffenhir ***@***.***> het volgende geschreven:﻿
Hi, what macOS version are you using? I built the arm version with macOS 13.6, so maybe a version > 13.6 may be required

**Comment by Steffenhir** [comment]
Please let me know if updating your OS worked 👍

**Comment by bartvanhoyland** [comment]
I will!Thank you for getting back to me so fast.Best,BartVerstuurd vanaf mijn iPhoneOp 13 jan. 2024 om 09:08 heeft Steffenhir ***@***.***> het volgende geschreven:﻿
Please let me know if updating your OS worked 👍

**Comment by bartvanhoyland** [comment]
Hi,

After the update all is working now!

Thx for the advice.

Best,

Bart

**Comment by Steffenhir** [comment]
Thank you, that's good to hear! What version did you update to?

**Comment by bartvanhoyland** [comment]
I updated to Sonoma 14.2.1
