### ISSUE TITLE
Graxpert won't open

### ISSUE THREAD

**Issue by aeshierry** [Steffenhir/GraXpert#121]
After I install Graxpert. I click on the downloaded file that says welcome to the graxpert set up wizard with two choices. Repair or Remove program. I just want to open the program ? Doing somethink wrong?

**Comment by Steffenhir** [comment]
Hi, the downloaded file is only an installer. To start the program, you can search for GraXoert or go into the folder in which you installed it, and start the .exe

**Comment by aeshierry** [comment]
Fixed-
