### ISSUE TITLE
Windows 11 Install fails

### ISSUE THREAD

**Issue by Bodrero** [Steffenhir/GraXpert#122]
I have 2 different windows 11 machines.  GraXpert installs fine on one, the other as soon as a click the executable, I get a spining icon, then it stops and nothing is installed.

Any ideas, I have disabled all virus software.

**Comment by schmelly** [comment]
Hi @Bodrero, that's strange.

Can you please try to install via a terminal with the following command:
`.\GraXpert-2.1.0-win64.msi /log graxpert_install.log`

This should create a logfile for the installation run named `graxpert_install.log` in the directory from which you started the installation procedure. Please have a look if you can spot any hints for an error in that logfile.

Best regards and CS
David

**Comment by Triffid-ger** [comment]
Same here with version 3.0.0. Trying to install from commandline gives me an "access denied" ("Zugriff verweigert") and thats it.
Started the commandline as administrator as well. Always the same result.

**Comment by Triffid-ger** [comment]
Found the solution: In some cases Windows does seem to lock access to downloaded installation files despite the user-clearance. This lock-state can be disabled from the file properties of the installation file.
