### ISSUE TITLE
Graxpert do not launch

### ISSUE THREAD

**Issue by Loupisteam** [Steffenhir/GraXpert#126]
I installed the last version of Graxpert 2.2.2 with the msi installation program.

The installation run apparently OK till the end on a Windows 7 PC.

I see the Graxpert icon, bt when I click on it I receive immediately the message: 

The Application could not start correctly (0xc000007b) click Ok to close the Application

Any suggestion

Thanks

**Comment by Steffenhir** [comment]
Hi, unfortunately GraXpert only runs on Windows 10 and newer.
CS Steffen

**Comment by Loupisteam** [comment]
Thanks ! At least it is a clear reason !
My 2nd Pc is Windows 11 and Graxpert works fine ... a bit uncomfortable to
have to switch back and forth !

Anyway, great SW ! Thanks again !

Christian

Le lun. 29 janv. 2024, 20:13, Steffenhir ***@***.***> a
écrit :
