### ISSUE TITLE
Script error - onnxruntime

### ISSUE THREAD

**Issue by beatmasterRS** [Steffenhir/GraXpert#132]
Unfortunately I get a script error when I try to start the program. This only occurs with the 3.x versions. I am using Windows 10, do you have any idea why this could be?

![error-win10](https://github.com/Steffenhir/GraXpert/assets/3855273/e05ee1e2-91b8-4eb4-a5cb-c58e923518d0)

Newest package is installed 
https://learn.microsoft.com/de-DE/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by schmelly** [comment]
Hi,
unfortunately I cannot reproduce your issue. I tested 3.0.0b1 on both my Windows 11 installation and a fresly installed virtual machine with Windows 10 Home, build 22H2. In the vm installation I did not install any additional packages like Visual C++ Redisdributable Package.

Is your Windows 10 installation up to date? Did you you install GraXpert in a non-standard directory?

Best regards
David

**Comment by avnirsoni** [comment]
I have the same issue.
I have Windows 10 Enterprise LTSC version 1809, fully up to date. Latest VC runtimie x86 and x64 installed.

I tried cloning repo and running directly in python, but that encountered an entierly different issue... missing s3_secrets, so imports don't work. Realise this should be a separate issue, but was only trying to run in in debug to see the cause of above issue.

Bit stuck...

**Comment by avnirsoni** [comment]
> I have the same issue. I have Windows 10 Enterprise LTSC version 1809, fully up to date. Latest VC runtimie x86 and x64 installed.
> 
> I tried cloning repo and running directly in python, but that encountered an entierly different issue... missing s3_secrets, so imports don't work. Realise this should be a separate issue, but was only trying to run in in debug to see the cause of above issue.
> 
> Bit stuck...

Ok, possibly found something. I tested GraXpert 3.02 on my laptop (same OS version etc) and it worked fine. Tested again on my PC and it didn't!

Additional info: I can't run starnet++ on my PC (unsupported), but it works fine on my laptop. Apparently it's due to a CPU instruction set that's required - AVX2 (required by TensorFlow, I think) which my very old CPU on my PC doesn't support.

Could this be what's happening here?

**Comment by Darkblade48** [comment]
> I have the same issue. I have Windows 10 Enterprise LTSC version 1809, fully up to date. Latest VC runtimie x86 and x64 installed.
> 
> I tried cloning repo and running directly in python, but that encountered an entierly different issue... missing s3_secrets, so imports don't work. Realise this should be a separate issue, but was only trying to run in in debug to see the cause of above issue.
> 
> Bit stuck...

I think I might have figured it out. I was also encountering this problem. Was using Win 10 Enterprise LTSC Version 1809, Build 17763.2686, on an Intel i5 8600. 

Tested on a different computer, running Win 10 Enterprise LTSC Version 21H2, Build 19044.4412, and GraXpert works fine there.

Not quite sure why this is the case, but unfortunately, my main desktop workhorse is the one running the older Win10 LTSC version.

**Comment by avnirsoni** [comment]
> I think I might have figured it out. I was also encountering this problem. Was using Win 10 Enterprise LTSC Version 1809, Build 17763.2686, on an Intel i5 8600.
> 
> Tested on an older laptop, but it's running Win 10 Enterprise LTSC Version 21H2, Build 19044.4412, and GraXpert works fine there.
> 
> Not quite sure why this is the case, but unfortunately, my main desktop workhorse is the one running the older Win10 LTSC version. My cheapo old laptop is the one running the newer LTSC version.

Thanks @Darkblade48 I still think this is hardware related - most likely CPU supoort of AVX or AVX2 instruction set - see my comment https://github.com/Steffenhir/GraXpert/issues/132#issuecomment-2103505885

**Comment by Darkblade48** [comment]
> > I think I might have figured it out. I was also encountering this problem. Was using Win 10 Enterprise LTSC Version 1809, Build 17763.2686, on an Intel i5 8600.
> > Tested on an older laptop, but it's running Win 10 Enterprise LTSC Version 21H2, Build 19044.4412, and GraXpert works fine there.
> > Not quite sure why this is the case, but unfortunately, my main desktop workhorse is the one running the older Win10 LTSC version. My cheapo old laptop is the one running the newer LTSC version.
> 
> Thanks @Darkblade48 I still think this is hardware related - most likely CPU supoort of AVX or AVX2 instruction set - see my comment [#132 (comment)](https://github.com/Steffenhir/GraXpert/issues/132#issuecomment-2103505885)

I don't think this is the case. 

[Intel i5 8600 ](https://www.intel.com/content/www/us/en/products/sku/129937/intel-core-i58600-processor-9m-cache-up-to-4-30-ghz/specifications.html)

[Intel 6200U (laptop)](https://ark.intel.com/content/www/us/en/ark/products/88193/intel-core-i5-6200u-processor-3m-cache-up-to-2-80-ghz.html)

Under 'instruction sets' both CPUs are seen to have AVX2 support. Furthermore, my (older) laptop with the older 6200U CPU is able to open and use GraXpert with no problems, while my (newer) desktop with the 8600 CPU isn't.

I started another issue [here](https://github.com/Steffenhir/GraXpert/issues/156), and @Rikyf3 indicated that this seems to be a Windows version related problem...
