### ISSUE TITLE
Graxpert v3 Python error

### ISSUE THREAD

**Issue by KANeuge** [Steffenhir/GraXpert#137]
Unable to run Graxpert with Pixinsight. It will start up independently of PixInsight. Any information on how to resolve this? I uninstalled all versions of Graxpert and reinstalled and rebooted. On all current versions of Pixinsight as well
![Graxpert Error](https://github.com/Steffenhir/GraXpert/assets/167926635/619cedb2-c9d5-4b86-a747-5260d46b8ea3)

**Comment by schmelly** [comment]
Hi,

please delete the folder `%localappdata%\GraXpert\GraXpert\bge-ai-models`, start GraXpert in standalone mode and try to (re-) install the appropriate models as described in this video:
https://www.youtube.com/watch?v=ZDqvIn5Vnig

Best regards
David

**Comment by schmelly** [comment]
Hi again,

for macOS users the appropriate path for the background extraciton models would be: `~/Library/Application Support/GraXpert/bge-ai-models`.

If you face a similar issue regarding the denois model the last part of the paths changes to: `.../denoise-ai-models`

Best regards
David

**Comment by KANeuge** [comment]
THANK YOU! That worked
