### ISSUE TITLE
GraXpert 3.0.0 not working on Windows 11

### ISSUE THREAD

**Issue by dglawdzin** [Steffenhir/GraXpert#139]
I had no issues with GraXpert in the past and was using it mostly with PixInsight. However, after a recent upgrade to the latest version. It doesn't behave properly. BE and Denosie are not working directly from the app (see logs). From the Pixinsight level, it doesn't do anything. It just stretches the image. I tried uninstalling it with fresh installation
[graxpert.log](https://github.com/Steffenhir/GraXpert/files/15137950/graxpert.log)
, but always with the same result. 
Please advise.

**Comment by Steffenhir** [comment]
Hi, it looks like the image you used has 4 channels. Does it by any chance have a transparency channel? This is not supported by GraXpert yet.

**Comment by dglawdzin** [comment]
I just picked a random image to generate the logs. I have the same issues across all my pictures—Raw, stacked, processed, etc. I forgot to mention that all graphic drivers are also up to date.

**Comment by Steffenhir** [comment]
Could you send me one of your images so I can have a closer look what is causing the issue?

**Comment by dglawdzin** [comment]
Ok, I think I managed to solve this as it was driving me nuts ;) I reinstalled it again, but this time, I also deleted the ...AppData\Local\GraXpert folder, which was left behind after the uninstall option. For some reason, this worked
