### ISSUE TITLE
instalation problem on windows

### ISSUE THREAD

**Issue by spockpics** [Steffenhir/GraXpert#140]
Hallo! i can not install 3.0.0 and getting the following error: c\user\....\appdata\
lokal\programs\Graxpert\Graxpert.exe
Verify that you have acces to that directory
the installation of the 2.2.2 version was without any problems 
do you know how i can fix this?
thank you Michael

**Comment by schmelly** [comment]
Hi Michael,

unfortunately I don't know why the default location does not work for your. You could try to install to a non-default location like `c:\graxpert\`. Please note that `c:\Program Files\graxpert` will not work as this would require administrator privilege and the installer is meant to be a user installation.

CS, David

**Comment by spockpics** [comment]
Hallo David!
Thank you for your e-mail!
I repeated the Download I would say about 30 times and I don’t know why it
suddenly works!
Thank you! Greetings Michael

-- 
Michael Wanke

Von: schmelly ***@***.***> ***@***.***>
Antworten: Steffenhir/GraXpert
***@***.***>
***@***.***>
Datum: 6. Mai 2024 at 16:16:43
An: Steffenhir/GraXpert ***@***.***>
***@***.***>
CC: spockpics ***@***.***> ***@***.***>, Author
***@***.***> ***@***.***>
Betreff:  Re: [Steffenhir/GraXpert] instalation problem on windows (Issue
#140)

Hi Michael,
