### ISSUE TITLE
GraXpert 3.0 on Windows missing AI files

### ISSUE THREAD

**Issue by Blanshan91** [Steffenhir/GraXpert#143]
I installed GraXpert 3.0 but is missing the AI files (shows none) and does not give me a prompt to download.   Any clue why this isnt working?   Can you provide a download link to the AI files used?

**Comment by schmelly** [comment]
Hi,

please cf.: https://github.com/Steffenhir/GraXpert/issues/136

CS, David

**Comment by Blanshan91** [comment]
Yep, I had manual time set, that fixed it, thanks for the quick response!!
