### ISSUE TITLE
Exit Error 1 in Pixinsight when using Denoise

### ISSUE THREAD

**Issue by KANeuge** [Steffenhir/GraXpert#144]
When using GraXpert Denoise in Pixinsight process completes almost immediately after initiating and PI shows an exit error of 1. Not sure what is going on. On current PI and GraXpert and latest denoise AI-Model 1.1.0. Appears to work fine with standalone GraXpert but not in PI.

**Comment by schmelly** [comment]
Hi,
you might want to use pre-release 3.0.1 from here: https://github.com/Steffenhir/GraXpert/releases/tag/3.0.1

There was an error in the cli interface where we incorrectly assigned available remote bge-model versions to the available remote denoise-model versions.

CS, David
