### ISSUE TITLE
Unknown error using denoise on WIN10

### ISSUE THREAD

**Issue by TomZAK72406** [Steffenhir/GraXpert#147]
After change to GraxPert 3.0 the background reduction is working very fast but denoising creates error. I have added a log-file.
[Fehlermeldung_GraxPert_3_0.docx](https://github.com/Steffenhir/GraXpert/files/15198331/Fehlermeldung_GraxPert_3_0.docx)

**Comment by Steffenhir** [comment]
Hi, there is some kind of issue when trying to run the AI on your GPU. Could you please try to install GraXpert v3.0.2 and disable hardware acceleration in the advanced menu on the right?

**Comment by TomZAK72406** [comment]
Hi Steffen Tranks for your fast response. I will try and give you feedback. All the best Thomas Von meinem IPhone gesendet Am 05.05.2024 um 18:03 schrieb Steffen Hirtle ***@***.***>:﻿
Hi, there is some kind of issue when trying to run the AI on your GPU. Could you please try to install GraXpert v3.0.2 and disable hardware acceleration in the advanced menu on the right?

**Comment by TomZAK72406** [comment]
Dear Steffen

 

Thank you a lot. It is working now with good results.

You´ve done a great job.

 

All the best 

Thomas

 

Von: Steffen Hirtle ***@***.***> 
Gesendet: Sonntag, 5. Mai 2024 18:03
An: Steffenhir/GraXpert ***@***.***>
Cc: TomZAK72406 ***@***.***>; Author ***@***.***>
Betreff: Re: [Steffenhir/GraXpert] Unknown error using denoise on WIN10 (Issue #147)

 

Hi, there is some kind of issue when trying to run the AI on your GPU. Could you please try to install GraXpert v3.0.2 and disable hardware acceleration in the advanced menu on the right?
