### ISSUE TITLE
cx_Freeze error unrelated to AI model

### ISSUE THREAD

**Issue by Darkblade48** [Steffenhir/GraXpert#156]
![cx_Freeze Error](https://github.com/Steffenhir/GraXpert/assets/40435344/d3a28a0d-1cb1-42c2-8685-d3516447ed94)

Hello everyone, 

I am encountering a cx_Freeze error that is unrelated to the more commonly found one related to AI models. 

I am currently using the standalone Windows version of GraXpert, version 3.0.2. 

My current computer specs are:
Windows 10 Enterprise LTSC Version 1809 Build 17763.2686
Intel Core i5 8600
MSI RTX 4060
16 GB DDR4 RAM @ 2666 MHz
ASRock H370M-ITX/ac LGA1151 motherboard

Interestingly, when I try on an older laptop, the same version of GraXpert opens with no problem (computer specs below):
Windows 10 Enterprise LTSC Version 21H2 Build 19044.4412
Intel Core i5 6200U
Onboard graphics card only
8 GB RAM 

Does anyone know if there was a major change between 1809 and 21H2 and/or a dependency that is only available in the newer 21H2 version?

**Comment by Rikyf3** [comment]
DirectML, that is used for AI, was introduced in windows 10 1903. If it is possible I advice you to upgrade to the latest version of windows and test if doing so fixes the issue. I see that you have a LTSC version so maybe upgrading does not work for you :(

**Comment by Darkblade48** [comment]
Unfortunately, it's difficult to upgrade directly from one version of LTSC to the next (by design, of course). I'll have to see what I can do about formatting my desktop and upgrading to 21H2. 

In the meantime, I guess I'll use my slower laptop, which at least has 21H2 installed on it!

Thanks for the answer; I guess that confirms my suspicion that there was a missing dependency on older Win10 versions...
