### ISSUE TITLE
Graxpert 3.0.2. hangs in Windows 11

### ISSUE THREAD

**Issue by ptrimby** [Steffenhir/GraXpert#161]
Hi, When starting up Graxpert -from shortcut, run as admin or fro. exe location, I get a full screen white window and little else.  Log file is attached

[graxpert.log](https://github.com/user-attachments/files/15523673/graxpert.log)

**Comment by Legacy281249** [comment]
Just happened to me too, exactly the same

**Comment by Rbcody** [comment]
Same here.  It has been working fine until today, but now it freezes on startup. Uninstalling and reinstalling makes no difference.

**Comment by schmelly** [comment]
Hi guys,

thanks for reporting. we had a service outtage on our object storage and it should work again. Please re-open if you still have issues.

CS, David
