### ISSUE TITLE
Wont install

### ISSUE THREAD

**Issue by Markydotcom** [Steffenhir/GraXpert#165]
H
I'm trying to install GraXpert on a new pc.
Whatever version I download the installer will run but wont complete and throws a code.

![Screenshot 2024-06-12 022251](https://github.com/Steffenhir/GraXpert/assets/168020659/970c7378-6de9-4d8f-878e-72c535397b9d)

hope you can help with this

thanks

Markydotcom 
Edition	Windows 11 Pro
Version	22H2
Installed on	‎12/‎06/‎2024
OS build	22621.3737
Experience	Windows Feature Experience Pack 1000.22700.1009.0

Device name	Astro-Beard-Main
Processor	AMD Ryzen 7 7735HS with Radeon Graphics           3.20 GHz
Installed RAM	32.0 GB (27.7 GB usable)
Device ID	0132E8D6-980D-4A58-895D-5D315E964185
Product ID	00331-20314-51954-AA348
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by schmelly** [comment]
Hi,

that error message is new to us. It might indicate a permission issue of your Windows user accessing the folder `C:\Temp`. Revisiting those permissions might help, cf. the following article for some other software:
https://help.krisp.ai/hc/en-us/articles/8083286001820-Error-during-installation-2502-and-2503#h_01HNCW0XCN8AJCWK84K8MQVY7Y

CS, David

**Comment by Markydotcom** [comment]
Hi,

Followed the instructions supplied, downloaded sucessfully and is working as on my other computers!

Many,many thanks.

Markydotcom.

**Comment by schmelly** [comment]
Hi, I'm glad you could get it to work!

CS, David
