### ISSUE TITLE
Non carica modelli Ai gradienti e denoise 

### ISSUE THREAD

**Issue by carulli** [Steffenhir/GraXpert#166]
Ho installato l'ultima versione la 3.0.2 nella directory assegnata C:\Users\Davide\AppData\Local\Programs , i modelli Ai sono stati installati in C:\Users\Davide\AppData\Local , il programma si apre regolarmente ma se voglio utilizzare i modelli Ai nella pagina a destra non li vede , succede solo a me? 
![GraXpert _ Release_ 'Umbriel' (3 0 2) 12_06_2024 17_33_06](https://github.com/Steffenhir/GraXpert/assets/172521562/560d3100-b5f6-41ec-9054-944b923c4363)

**Comment by carulli** [comment]
risolto era la sincronizzazione dell'orario del mio sistema con i server da cui si scaricano i modelli AI...ora funziona tutto

**Comment by schmelly** [comment]
Hi, glad you solved it!

CS, David
