### ISSUE TITLE
SSLError - certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)

### ISSUE THREAD

**Issue by wookash** [Steffenhir/GraXpert#169]
Hi, due to corporate restrictions I cannot download AI model to my Mac. I was able to launch the app and download them on another Windows machine. Where do I put them on Mac (folder/location)?

**Comment by wookash** [comment]
I also don't get a prompt to download models on macOS, I did get that prompt on Windows (3.0.2)

**Comment by wookash** [comment]
It now looks like it's a problem with SSL certificate, that's why I cannot select or download the models.. here's the error:

`
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='minio.schmelly.de', port=443): Max retries exceeded with url: /graxpert-denoise-ai-onnx?location= (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))>
`

**Comment by wookash** [comment]
I can access url minio.schmelly.de from the webbrowser

**Comment by wookash** [comment]
[log.txt](https://github.com/user-attachments/files/15885877/log.txt)
and here's the full console content

**Comment by schmelly** [comment]
Hi,

I cannot reproduce your issue and suspect you are trying to connect via your company network through a proxy server. We do serve the ai models via minio which is an s3 compatible object storage; data is transfered via https. In front of minio we have a reverse proxy with a valid certificate issued by "Let's Encrypt".

The macOS base folder GraXpert's user data is `/Users/<your_username>/Library/Application Support/GraXpert`.

CS, David

**Comment by wookash** [comment]
Thanks, you're probably right (I'm not really behind a company VPN, but there has to be some traffic filtering happening). I was able to copy the AI models from windows machine to the location you've given and now I'm able to select these AI models. So it kind of works. I think we can close this now - unless you think otherwise.
