### ISSUE TITLE
Starting fails (Linux OS)

### ISSUE THREAD

**Issue by waldbaer59** [Steffenhir/GraXpert#44]
When trying to start the program I get an error message:

> Traceback (most recent call last):
>   File "gui.py", line 942, in <module>
>   File "ui_scaling.py", line 16, in get_scaling_factor
>   StopIteration
> [5935] Failed to execute script 'gui' due to unhandled exception!

My system is Arch Linux (5.17.4-arch1-1). DE is xfce rel 4.16 .

Best regards 
Stephan

**Comment by schmelly** [comment]
thanks for reporting! will be fixed in in the next release
