### ISSUE TITLE
buttons and fonts not usable in newer versions

### ISSUE THREAD

**Issue by Holgervisitinggithub** [Steffenhir/GraXpert#68]
Version 0.1.3 was the last usable one on my system (Win 10 Pro, i7-6700, 16GB RAM, Nvidia RTX 2060; screen: LG C9 65", resolution: 4096x2160; connected through HDMI). The following versions all had tiny buttons with micro fonts (see picture with side-by-side comparison).

![Graxpert_version-comparison](https://user-images.githubusercontent.com/111205077/202914316-41da0f86-4418-41f6-b399-9f520cade9a5.PNG)

**Comment by Steffenhir** [comment]
We intentionally decreased the font size in later versions, but in some cases the DPI is not detected correctly, which causes even smaller font sizes than intended. We plan to implement a slider to control the font size manually for those cases, in which the automatic DPI detection fails.

**Comment by don1006** [comment]
I am having the same issue.    I am using Win 11 pro, i9-12900, 64GB ram, Nvidia RTX 3070,  Screen is LG 42 inch, C2, resolution 3840 x 2160.   I have tried every setting nothing works.    I downloaded version 0.1.3 and works like to suppose to.   thank you for your time.

**Comment by Steffenhir** [comment]
@Holgervisitinggithub @don1006 We slightly increased the default font size with the newest version v1.0.5. However, we will still implement a slider for adjusting the font size manually in the next version.

**Comment by Holgervisitinggithub** [comment]
Thank you for the great software and your efforts to continuously improve it!
v1.0.5 doesn't work for me neither, so I am waiting for the version with the slider
<img width="1154" alt="Comp_2" src="https://user-images.githubusercontent.com/111205077/229291268-ff8fad05-4d88-428f-b052-627e39553b4d.PNG">

**Comment by Steffenhir** [comment]
@Holgervisitinggithub With the new version v1.0.6, you can find a slider in the advanced settings for adjusting the UI size. The advanced settings can be opened by clicking on the blue 'Advanced' button on the right.

**Comment by Holgervisitinggithub** [comment]
Thank you for this new version, which makes this wonderful program now working for me again!
