### ISSUE TITLE
Slider Controls

### ISSUE THREAD

**Issue by danieldh206** [Steffenhir/GraXpert#72]
The sliders can be difficult to finely control for people with disabilities and/or use a non-standard mouse. A manual entry box, plus and minus buttons, or the ability to control the sliders with arrow keys or plus minus keys would be very helpful.

**Comment by danieldh206** [comment]
Looks like one of the first sliders is at [Line 294](https://github.com/Steffenhir/GraXpert/blob/main/src/gui.py#L294). I know Python and will also take a look, but have not worked with Tkinter GUI modules.

**Comment by danieldh206** [comment]
something like:
        def move(self,n):
            self.angle+=.1
            self.position=self.findcoord()
            self.canvas.coords(self.current,self.position)

          self.master.bind('<Left>',lambda event,arg=.1:self.move(event,arg))
          self.master.bind('<Right>',lambda event,arg=-.1:self.move(event,arg))

**Comment by Steffenhir** [comment]
The next version will have entry boxes for manual entry and you will also be able to use the up and down arrow keys.

**Comment by Steffenhir** [comment]
Here it is: https://github.com/Steffenhir/GraXpert/releases/tag/v1.0.5

**Comment by danieldh206** [comment]
Excellent, Thank you

**Comment by danieldh206** [comment]
I see issue while using the arrow keys, the arrow keys move by one. This causes the "Smoothing" box to jump between 0 and 1. I think the arrow keys should move by .1.

**Comment by danieldh206** [comment]
When I push the up arrow key the slider moves down and when I push the down arrow key the slider moves up. My keyboard is the standard English keyboard.

**Comment by Steffenhir** [comment]
Thank you for testing! This behavior was caused by the default binding of arrow keys in the ttk.Scale class. With this new version it should work as intended when the entry box or the slider is focused.

https://github.com/Steffenhir/GraXpert/releases/tag/v1.0.5

**Comment by danieldh206** [comment]
Arrow keys work correctly now. The only issue I am finding now is the box for soothing needs to be slightly bigger. I tried on different monitors and any two digit number like 0.1 fit correctly but any three digit number like 0.43 does not fit.
![Soothing_box](https://user-images.githubusercontent.com/24887442/228292766-1265adcb-1277-4077-ab1f-568097c718c1.jpg)

**Comment by Steffenhir** [comment]
Could you try if it works now?
https://github.com/Steffenhir/GraXpert/releases/tag/v1.0.5

**Comment by danieldh206** [comment]
The digits fit correctly. 
If I found the correct line in slider.py I wonder if adding `anchor=CENTER` to line 24 will center the numbers inside of the entry box. I know the TTK anchor command sets the position of a label in a frame, but wonder if it will also work for entry boxes. 
Centering the number is for purely for cosmetic reasons.
