### ISSUE TITLE
M1 MAC running Ventura 13.4

### ISSUE THREAD

**Issue by Marcyf64** [Steffenhir/GraXpert#76]
Hi - I installed GraXpert, got passed the security protection.  When I double click the icon I get the dreaded spinning beachball.  Any suggestions?

**Comment by schmelly** [comment]
Hi Marcy,

did you install/copy GraXpert to the Applications folder? If not, please do so. 

The following steps worked for me on a test machine in a reproducible way:

- (if installed previously) remove the old GraXpert installation from the applications folder (i.e., move it to the trash).
- double click on the downloaded .dmg. MacOS 'mounts' the .dmg file and should open it in a new window in Finder.
- copy 'GraXpert' from this window into the applications folder (e.g., via drag & drop)

From here it gets a little bit strange and I have to open GraXpert always two times until it starts:

- Start GraXpert via double click from the programs folder. After a short time MacOS complains that it can't analyze the application.
- Open GraXpert again, but this time via ctrl + right-click -> Open. A slightly different dialog should open, where you have to explicitly confirm the launch again. As I understand it, this step is equivalent to allow application startup via System Preferences/Security & Privacy/General (just a bit shorter). Unfortunately, this ctrl + right-click "workaround" won't work the first time you open it - for whatever reason.

Afterward you should be able to open GraXpert simply via double click. These steps have to be repeated for each new GraXpert release / download.


If you did install GraXpert to the Applications folder please attach the Graxpert log. Should be in the following folder:
~/Library/Application Support/GraXpert/GraXpert/Logs/


Best regards
David

**Comment by Marcyf64** [comment]
Hi David - thanks for your reply.  It didn't make it to the applications folder on my original download.  Once I moved it in there and then gave the privacy approval it opened right up!  Look forward to using it.  Thanks so much
Marcy
http://www.marcycohen.com



 

    On Monday, May 29, 2023 at 04:56:28 PM EDT, schmelly ***@***.***> wrote:  
 
 


Hi Marcy,

did you install/copy GraXpert to the Applications folder? If not, please do so.

The following steps worked for me on a test machine in a reproducible way:
   
   - (if installed previously) remove the old GraXpert installation from the applications folder (i.e., move it to the trash).
   - double click on the downloaded .dmg. MacOS 'mounts' the .dmg file and should open it in a new window in Finder.
   - copy 'GraXpert' from this window into the applications folder (e.g., via drag & drop)

From here it gets a little bit strange and I have to open GraXpert always two times until it starts:
   
   - Start GraXpert via double click from the programs folder. After a short time MacOS complains that it can't analyze the application.
   - Open GraXpert again, but this time via ctrl + right-click -> Open. A slightly different dialog should open, where you have to explicitly confirm the launch again. As I understand it, this step is equivalent to allow application startup via System Preferences/Security & Privacy/General (just a bit shorter). Unfortunately, this ctrl + right-click "workaround" won't work the first time you open it - for whatever reason.

Afterward you should be able to open GraXpert simply via double click. These steps have to be repeated for each new GraXpert release / download.

If you did install GraXpert to the Applications folder please attach the Graxpert log. Should be in the following folder:
~/Library/Application Support/GraXpert/GraXpert/Logs/

Best regards
David
