### ISSUE TITLE
Anwendung lösst sich unter MacOS Sonoma (14.0) nicht mehr bedienen

### ISSUE THREAD

**Issue by SavouryMonkey** [Steffenhir/GraXpert#78]
Hallo zusammen, leider musst ich nach dem Update feststellen, dass sich die Anwenung nicht mehr wie gewohnt bedienen lässt. 
Ausklappmenüs gehen nicht mehr, buttonklicks brauchen 3-4 schnelle klicks bis sie gehen, etc. 

Grüße und weiter so!

**Comment by Steffenhir** [comment]
Hallo, meinst du mit dem Update den Umstieg auf eine macos Beta oder eine neue GraXpert Version? Bei Problemen mit der neuen macos Beta können wir leider erstmal nichts machen.

**Comment by SavouryMonkey** [comment]
@Steffenhir Seit dem umstieg auf eine neue MacOS Version, 14.0 - Sonoma. Korrekt. Es handelt sich jedoch nicht mehr um die Beta sondern die GM welche am 26.09. für alle Anwender zur Verfügung steht. Folglich hielt ich es für Klug den Fehler im Vorfeld mal zu melden. Ich konnte es nur auf M1 als auch M2 testen, auf beiden meiner Systeme bestehen die angesprochenen Probleme. 

Grüße.

**Comment by Steffenhir** [comment]
Danke für den Hinweis! Ich befürchte, dass wir da erstmal nicht viel dagegen tun können, wenn das Problem auf Seiten von Tkinter oder macOS liegt. Es wäre schön wenn du beim finalen Release von macOS 14 nochmal ein Update geben könntest, ob es sich verbessert hat.

**Comment by michael-ring** [comment]
Erst mal vielen Dank für das Tool, es ist einfach genial....

Leider bestehrt auch in der Release Version das Problem, die App ist nicht mehr bedienbar.

Ich habe ein anderes Issue aufgemacht denn dank AI könnte im Moment helfen das man die App von Commandline aus bedienen kann um die Zeit zu überleben bis das Tkinter angepasst ist...

Michael

**Comment by michael-ring** [comment]
Ich muss mich verbessern, irgendwann fangen die Buttons an zu funktionieren, es fühlt sich so an als ob das ganze mit dem Focus Handling zu tun hat. 

Wenn ich auf den Zahlenwert bei Saturation clicke und dann ggf. auf die Werte bei Points per Row oder Grid tolerance dann sehe ich irgendwann das ich einen Input Focus habe...

Danach kann ich dann mit der Tastatur Aktionen auswählen, ist aber nicht einfach da man auf den Buttons nicht sieht wo der Input Focus gerade ist.

Was einigermassen gut funktioniert ist das file über commandline zu laden, AI einzustellen und dann das Bild zu berechnen. Man muss halt mitzählen wie oft man TAB oder Shift-TAB drücken muss um auf dem richtigen Button zu sein.

**Comment by michael-ring** [comment]
Hier ein absoluter Minimal Fix für den AI Branch, mit Keyboard Shortcuts kann man arbeiten, zusätzlich noch etwas code um graxpert als Modul nutzen zu können.

Command-L lädt ein File
Command-C berechnet den Background
Command-S speichert das Ergebnis.

Ich habe 0,0% Ahnung von tkinter und mir ist daher unklar wieso ich noch ein dummy Argument für calculate und safe_image einführen musste, ohne die gab es diesen Fehler:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
TypeError: Application.calculate() takes 1 positional argument but 2 were given
Exception in Tkinter callback 
```

```
diff --git a/graxpert/gui.py b/graxpert/gui.py
index c011376..2863561 100644
--- a/graxpert/gui.py
+++ b/graxpert/gui.py
@@ -2,6 +2,10 @@ import multiprocessing

 multiprocessing.freeze_support()

+import sys
+from os.path import dirname
+sys.path.append(dirname(dirname(__file__)))
+
 from graxpert.mp_logging import configure_logging, initialize_logging, shutdown_logging

 configure_logging()
@@ -157,7 +161,9 @@ class Application(tk.Frame):
         self.master.bind("<Control-y>", self.redo)                     # redo
         self.master.bind("<Command-z>", self.undo)                     # undo on macs
         self.master.bind("<Command-y>", self.redo)                     # redo on macs
-
+        self.master.bind("<Command-l>", self.menu_open_clicked)        # load
+        self.master.bind("<Command-c>", self.calculate)                # calculate
+        self.master.bind("<Command-s>", self.save_image)               # save

         #Side menu
         heading_font = "Verdana 11 bold"
@@ -503,7 +509,7 @@ class Application(tk.Frame):
         self.redraw_image()


-    def save_image(self):
+    def save_image(self,dummy):


        if(self.saveas_type.get() == "16 bit Tiff" or self.saveas_type.get() == "32 bit Tiff"):
@@ -625,7 +631,7 @@ class Application(tk.Frame):
             self.cmd.execute()
             self.redraw_image()

-    def calculate(self):
+    def calculate(self, dummy):

         if self.images["Original"] is None:
             messagebox.showerror("Error", _("Please load your picture first."))
```

**Comment by Steffenhir** [comment]
Vielen Dank! Wir werden die Shortcuts mit aufnehmen in die nächste Version

**Comment by Steffenhir** [comment]
@michael-ring @SavouryMonkey Könntet ihr mal testen, ob die arm64 Version bei Release v1.0.6cAI funktioniert. Ich habe tcl-tk auf 8.6.13 geupdatet, das sollte das Problem beheben.

**Comment by SavouryMonkey** [comment]
@Steffenhir  Jawoll, jetzt geht's wieder! Danke!
