### ISSUE TITLE
Batch/Commandline Nutzung von GraXpert

### ISSUE THREAD

**Issue by michael-ring** [Steffenhir/GraXpert#79]
Leider funktioniert GraXpert nicht mehr korrekt in der letzten Version von MacOSX.

Durch den AI Prozess sind aber die manuellen Schritte in der UI eigentlich komplett hinfällig.

Wie wäre es also ein Commandline Interface zu implementieren das es erlaubt das Source und das Destimation Image anzugeben und dann automatisch die AI Funktion aufzurufen.

Sowas wie:

/Applications/GraXpert.app/Contents/MacOS/GraXpert --source=x.xisf --target=y.xisf 

das wäre vermutlich das Minumum was nötig wäre um ein Bild umzuwandeln. Natürlich könnte man noch das Smoothing als PArameter einbauen aber das wäre schon die Creme auf dem Sahnerhäuchen.

Es ist sogar möglich die App noch zu bedienen über die Tastatur, allerdings geht der Dialog zum Biler öffnen nicht.....

**Comment by Steffenhir** [comment]
Eine Commandline Funktion wird es in der nächsten Version geben zusammen mit den Shortscuts

**Comment by schmelly** [comment]
@michael-ring with GraXpert `2.2.0` we have now implemented a second CLI iteration that supports processing of single images with the AI model.

Best regards and CS
David
