### ISSUE TITLE
Missing dependency `bg_model` in AI beta C

### ISSUE THREAD

**Issue by shekibobo** [Steffenhir/GraXpert#80]
When I open an XISF file, select AI for the Interpolation Method, and run `Calculate Background`, I get the following error dialog:

```
No file or directory found at /Applications/GraXpert.app/Contents/MacOS/bg_model
```

**Comment by Steffenhir** [comment]
Hi, you have to download the AI model at https://drive.google.com/drive/folders/1wVLMgrCGJk2J7922qrmKzMk71P1Ygbpy?usp=drive_link and unzip it. Then you can choose the directory of the bg_model folder in the advanced settings on the right, or you put it in the default directory for macOS /Applications/GraXpert.app/Contents/MacOS/bg_model

**Comment by shekibobo** [comment]
Perfect, that worked thanks! Can Is there a link to that somewhere that I should have seen?

**Comment by Steffenhir** [comment]
We advertised this Beta version with this Youtube video https://youtu.be/AzDDafSrZ7k?si=8srB6c0bN2-XTktq which includes all the explanations for installation, usage, and also how to contribute more training data
