### ISSUE TITLE
Release v1.0.6dAI startet nicht auf MacOSX X86_64

### ISSUE THREAD

**Issue by michael-ring** [Steffenhir/GraXpert#81]
Per Icon startet es nicht, wenn ich explizit das bianry starte kommt diese Meldung:

Last login: Thu Oct  5 21:15:07 on ttys001
/Applications/GraXpert.app/Contents/MacOS/GraXpert ; exit;
Parsing /Users/ring/.zshrc
ring@macbook-pro ~ $ /Applications/GraXpert.app/Contents/MacOS/GraXpert ; exit;
[80945] Failed to execute script 'gui' due to unhandled exception: No module named 'skimage.transform._warps'
[80945] Traceback:
Traceback (most recent call last):
  File "graxpert/gui.py", line 22, in <module>
  File "lazy_loader/__init__.py", line 77, in __getattr__
  File "importlib/__init__.py", line 126, in import_module
ModuleNotFoundError: No module named 'skimage.transform._warps'

Saving session...completed.
Deleting expired sessions...none found.

[Prozess beendet]

**Comment by michael-ring** [comment]
Latest vom AI branch direk aufgerufen startet einwandfrei....

**Comment by l4zy0n3** [comment]
```
File "graxpert/gui.py", line 22, in
File "lazy_loader/init.py", line 77, in getattr
File "importlib/init.py", line 126, in import_module
ModuleNotFoundError: No module named 'skimage.transform._warps'
```
Facing the same issue on Windows 11

**Comment by Steffenhir** [comment]
Thank you for the report, I will delete version v1.0.6dAI in the meantime and report back when I found the issue.

**Comment by BigBobDalton** [comment]
Not certain, but maybe this is an issue running on OSX-14?  I too cannot get the App to open

**Comment by Steffenhir** [comment]
The issue should be solved now. Release v1.0.6dAI should fix the issues with macOS Sonoma for the x86_64 version. The issues for the arm64 version were already fixed in the previous release v1.0.6cAI. Please let me know if it works.

**Comment by michael-ring** [comment]
Woks fine for me on X86_64 and ARM64.

**Comment by BigBobDalton** [comment]
Yes, I can confirm as well, it works on Mac OSX-14 x86_64
