### ISSUE TITLE
GraXpert fails to charge on Windows 11

### ISSUE THREAD

**Issue by jdef1** [Steffenhir/GraXpert#88]
Hi
After downloading the windows version V1.0.6, I get an error concerning TCL component.
![Capture d'écran 2023-10-18 113058](https://github.com/Steffenhir/GraXpert/assets/148332595/556de3a1-4b1a-46b0-9826-adf6cab2ea00)
![Capture d'écran 2023-10-18 114159](https://github.com/Steffenhir/GraXpert/assets/148332595/8eaf28f4-4425-48fe-b409-d49f8b4983e8)
Best regards

**Comment by schmelly** [comment]
Hi,

unfortunately I cannot reproduce this issue on a Windows 11 system with recent updates installed: I tested against this release: https://github.com/Steffenhir/GraXpert/releases/tag/v1.0.6
GraXpert-win64.exe

I'm a bit surprised of the different mentioned folders in your first screenshot: GraXpert is a Python application that has been packed by PyInstaller as a single executable. The executable is basically a self extracting archive including a small "bootloader" and embedded Python runtime. After extraction, the bootloader starts the actual Python application.

Now, on my machine the target directory for the unpacked archive is:
`C:\Users\<username>\AppData\Local\Temp\_MEI<random_number>`
I am missing this folder in your screenshot. Do you have some "non standard" Windows 11 installation in a sense that for instance you changed the %TEMP% directory? This might explain why the startup fails. You can verify the location of the %TEMP% folder inspecting your user's environment variable or by opening a command prompt and entering `cd %temp%`.

CS
David

**Comment by jdef1** [comment]
Hi
no the installation is standard, as due to a recent problem with windows update I had to fully reinstall the OS.
I succeeded to launch the program by elevating it to administrator level. Surely, a security parameter somewhere ...
Best regards.
Jacques
![Capture d'écran 2023-10-19 192100](https://github.com/Steffenhir/GraXpert/assets/148332595/a89a8b81-a037-4e5d-bd5c-049a098793c4)
![Capture d'écran 2023-10-19 191630](https://github.com/Steffenhir/GraXpert/assets/148332595/7ffc66a1-b268-483e-ab2e-a4d7e8430d44)

**Comment by schmelly** [comment]
@jdef1 I have created a test build that packages GraXpert as an .msi installer. Can you please try if this improves the situation? 

You can grab the test build here: https://github.com/schmelly/Background_extraction/releases/download/2.0.3/GraXpert-2.0.3-win64.msi

Many thanks and CS
David

**Comment by jdef1** [comment]
Hi DavidEvery thing was Ok during the installation. Thank-you.Best regradsJacquesenvoyé : 11 décembre 2023 à 20:31de : schmelly ***@***.***>à : Steffenhir/GraXpert ***@***.***>cc : jdef1 ***@***.***>, Mention ***@***.***>objet : Re: [Steffenhir/GraXpert] GraXpert fails to charge on Windows 11 (Issue ***@***.*** I have created a test build that packages GraXpert as an .msi installer. Can you please try if this improves the situation?You can grab the test build here: https://github.com/schmelly/Background_extraction/releases/download/2.0.3/GraXpert-2.0.3-win64.msiMany thanks and CS David—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by schmelly** [comment]
@jdef1 we have released GraXpert `2.2.0` that ships as an .msi installer on MS Windows.

Best regards and CS
David
