### ISSUE TITLE
CommandLine "needs" more parameters

### ISSUE THREAD

**Issue by tupolev** [Steffenhir/GraXpert#90]
I am writing a simple script to integrate Graxpert in the Pixinsight workflow. So far it works, BUT:

Commandline support for GraXpert, according to the docs, is only used for AI mode and AI mode does not need some parameters, so it sets (according to the code) default values when calling the calculate_background method. These default values cause unexpected effects in some processed images.

So one possible solution/improvement could be allowing to specify all parameters in the command line. I would extend the GUI of my script to set those parameters, so the user can test-run which parameters get a better result.

Another approach could be allowing to specify source and target image name and paths, but opening the graxpert GUI to let the user operate on it, as any of the Photoshop plugins, changing the save button to something like "save and return" instead of "save as", saving the changes but not changing the location of the file.

The script is this one https://github.com/tupolev/graxpertlauncher and basically shows a gui to fulfill the correction type, smoothing factor and executable path. Then launches graxpert command line and waits for finish of the command, reopening the target image (as graxpert generates a fixed name image) in Pixinsight.

How do you see it?  Is it doable?

EDIT: I've just verified. It's the AI mode which generates vignetting. But I have tried only one image with different algorithms. Maybe then it's a good idea to let the user choose the algorithm from the commandline :)

**Comment by Steffenhir** [comment]
Hi, the idea of starting GraXpert similar to a Photoshop Plugin sounds like a good idea. We started with only the AI method since this was an easy first step. If you experience vignetting with the AI method, it might help to crop the borders if they contain some kind of stacking artifacts.

**Comment by tupolev** [comment]
That's great. I'll try to try myself and also write those hints too for the user.

For now, the launcher works with the available options. If you finally release a version with the extended command line, I will extend the launcher for it properly :)

Thank you for this great app!!
