### ISSUE TITLE
2.0.1 Release Issue

### ISSUE THREAD

**Issue by David-Pyxis-Designs** [Steffenhir/GraXpert#91]
When I downloaded and installed `2.0.1` it opened and told me there was a newer version available.  It showed as `2.0.0` on the title bar and the About GraXpert is showing as `v1.0.6cAI`. I tried this twice to make sure I was not downloading the wrong version

<img width="459" alt="Screenshot 2023-10-25 at 10 11 44 AM" src="https://github.com/Steffenhir/GraXpert/assets/7002150/ff8e33b6-ca86-4683-a323-8b0730c349cb">

**Comment by Steffenhir** [comment]
Hi, is this the macOS-arm64 version? I always have to compile the macOS-arm64 version manually, so I may have forgotten to change the update the version number

**Comment by Steffenhir** [comment]
The issue should be solved now, you just have to download the arm64 version again. In general, we are always looking for new developers :) If you are interested you can join us in the Dark Matters Discord https://discord.gg/JQuS4Q8D

**Comment by david-koneksa** [comment]
I joined the discord yesterday but it was all in German and I could not find a language setting.

**Comment by David-Pyxis-Designs** [comment]
> The issue should be solved now, you just have to download the arm64 version again. In general, we are always looking for new developers :) If you are interested you can join us in the Dark Matters Discord https://discord.gg/JQuS4Q8D

Thanks for resolving this so quickly. I joined the discord server the other day but I couldn’t read most of it. Looks like German and I couldn’t find a way to translate into US English.

**Comment by Steffenhir** [comment]
Most users on this server are german, but we are also happy to reply in English.  If you would like to help us, just write us in the GraXpert-chat channel.
