### ISSUE TITLE
Python version of GraXpert

### ISSUE THREAD

**Issue by AstroDeepSky** [Steffenhir/GraXpert#96]
Hi,

I'm using command line mode to run GraXpert from PixInsight with a dedicated small javascript.
Due to problems reported in another post (Command line needs few enhancements), I'm using Python version.

I run GraXpert with following command: python -m graxpert.main ...
File s3_secrets.py is not part of the package and so prevent the execution.
I guess you don't want to publish this file, however, you should change the implementation in such way that when s3_secret.py is not there, the automatic download of AI models is disabled and program run with model(s) provided manually.

AI background extraction is amazing :-)
Let me know if you want some help.

**Comment by schmelly** [comment]
Change commited and merged into main
